apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nn-devops-challenge.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nn-devops-challenge.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nn-devops-challenge.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nn-devops-challenge.name" . }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "{{ .Values.app.environment }}"
