apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
name: nn-devops-challenge
description: Helm chart for nn-devops-challenge Spring Boot app
keywords:
  - app
  - spring
maintainers:
  - email: chui274@gmail.com
    name: Sofía Fernández Moreno
type: application

