apiVersion: v2
version: 1.0.0
appVersion: 1.0.0
name: common
description: A Library Helm Chart for grouping common logic between all charts.
keywords:
  - common
  - helper
maintainers:
  - email: chui274@gmail.com
    name: Sofía Fernández Moreno
type: library